### ISSUE TITLE
Line 41 error

### ISSUE THREAD

**Issue by anthonykirkham** [TheSharpieOne/angular-off-click#10]
Hi There,

Looks like there is a minor error on line 41 of offClick.js

It currently says `attrs.$observe` instead of `attr.$observe`

Thank.

**Comment by TheSharpieOne** [comment]
This appears to have been introduced by @Kuzmin in #9. I didn't notice it, and this is why I need to write some tests :(

**Comment by Kuzmin** [comment]
Oh jesus, I corrected this typo but forgot to push it. Sorry!
