### ISSUE TITLE
Consider removing isolated scope

### ISSUE THREAD

**Issue by elado** [TheSharpieOne/angular-off-click#11]
Can't apply on element that already asks for isolated scope.
Functions can be extracted with `$parse`. See http://luxiyalu.com/angular-directive-click-elsewhere/

**Comment by TheSharpieOne** [comment]
Fixed, made the whole thing more in line with how angular handles events.  See https://github.com/angular/angular.js/blob/g3_v1_2/src/ng/directive/ngEventDirs.js#L54

**Comment by elado** [comment]
Thanks!
