### ISSUE TITLE
Syntax Error: Token '.' not a primary expression at column 1 of the expression  ['.modal-dialog']

### ISSUE THREAD

**Issue by bawigga** [TheSharpieOne/angular-off-click#16]
> The optional off-click-filter attribute is a comma separated list of selectors that will not trigger off-click when they are clicked.

I have the following attribute: `off-click-filter=".modal-dialog"`

However, I get the following error [here](https://github.com/TheSharpieOne/angular-off-click/blob/0d4096d8dd04abd5fc40b1f80b2789d8b86bc6a2/offClick.js#L55)

```
Error: [$parse:syntax] Syntax Error: Token '.' not a primary expression at column 1 of the expression [.modal-dialog] starting at [.modal-dialog].
```

**Comment by TheSharpieOne** [comment]
This accepts an expression, so you can pass a reference to a string or use single quotes to create a string literal like this: `off-click-filter="'.modal-dialog'"`

**Comment by TheSharpieOne** [comment]
This was a recent change, I updated the README to show the use of single quotes to indicate a string literal.
