### ISSUE TITLE
Elements at (0, 0) are ignored

### ISSUE THREAD

**Issue by alexlawrence** [TheSharpieOne/angular-off-click#17]
We are currently executing specs which validate angular-off-click works correctly on our pages. In the specs we use placeholder divs which have no dimensions. When we simulate a click event it will have a pageX and pageY of 0. 

It could also be that on a real page a button is on the upper left and the user clicks on (0, 0). What do you think? 

Could we simply remove the following line? https://github.com/TheSharpieOne/angular-off-click/blob/master/offClick.js#L17

**Comment by TheSharpieOne** [comment]
Yeah, that came from #3... probably shouldn't had added it to the solution.  I'll remove it.

**Comment by alexlawrence** [comment]
I read through the issue and I also find it very interesting, not to say potentially problematic. However, if you are interested in solving this I wouldn´t recommend for just checking pageX and pageY for a value 0. As far as I know these are valid values. Thanks for the removal.
