### ISSUE TITLE
Doesn't work on Safari Mobile

### ISSUE THREAD

**Issue by TravisTX** [TheSharpieOne/angular-off-click#20]
Safari Mobile has a bug [described here](https://developer.mozilla.org/en-US/docs/Web/Events/click#Safari_Mobile) which is preventing offclick from seeing the click event on the document object.

**Comment by ivamluz** [comment]
Is it supposed to be working now? I tested on this plunker (http://plnkr.co/edit/baQlrVYL8ojdOMwCRQ39?p=preview) using version 0.0.6 and it seems it's still not working on Safari mobile browsers (tested on both iPad and iPhone - versions 8.1 and 7.1.1, respectively).

**Comment by ivamluz** [comment]
Forget it. Just noticed it's fixed on master. @TheSharpieOne, any changes to have tag 0.0.7 created soon?

**Comment by TheSharpieOne** [comment]
Sorry about that. Done.
