### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TravisTX** [TheSharpieOne/angular-off-click#22]
Could you consider adding a license to this code?  At the moment even though the code is online, it's still [assumed](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) to be fully copyrighted and not able to be used in other projects.

[Choose a License](http://choosealicense.com/)

[How to add a license in github](https://help.github.com/articles/open-source-licensing/#how-can-i-go-back-through-my-public-repositories-and-give-them-licenses)

**Comment by TheSharpieOne** [comment]
Well, that was easy.  I didn't know GitHub had that license thing when you name a file `LICENSE.md`.

**Comment by TravisTX** [comment]
Thanks :)
