### ISSUE TITLE
Doesn't trigger with $rootScope.$evalAsync

### ISSUE THREAD

**Issue by hagayl** [TheSharpieOne/angular-off-click#23]
The listener's callback isn't triggered immediately, only after another user action.
Using ```$rootScope.$apply``` instead of ```$rootScope.$evalAsync``` worked for me.

**Comment by TheSharpieOne** [comment]
That may cause problems.  See: http://www.bennadel.com/blog/2605-scope-evalasync-vs-timeout-in-angularjs.htm

**Comment by Ricardo-Marques** [comment]
Closing this, seems like it's no longer an issue.
