### ISSUE TITLE
Not working for table row in ng-repeat-end

### ISSUE THREAD

**Issue by demonspeed** [TheSharpieOne/angular-off-click#25]
Consider the following:
```
<table>
  <tr ng-repeat-start="item in list" ng-click="show = true" off-click="show = false" 
off-click-filter="'.no-trigger'">{{item}}</tr>
  <tr ng-repeat-end class="no-trigger" ng-show="show">I don't want to trigger off-click</tr>
</table>
```
Clicking on text "I don't want to trigger off-click" does trigger off-click. Maybe it has to do with ng-repeat and table semantics, because the issue is similar to having content inside table element without proper tr and td elements within, which also triggers off-click regardless of table selector.

**Comment by TheSharpieOne** [comment]
This probably has something to do with the way the script is lazily getting the elements that shouldn't trigger the off-click.

Can you throw together a fiddle or plunkr?

**Comment by RicardoAlmeidaMarques** [comment]
Resolved.
