### ISSUE TITLE
off-click-filter not working

### ISSUE THREAD

**Issue by ilyador** [TheSharpieOne/angular-off-click#29]
I tried multiple sectors but the off-click still goes through.

**Comment by TheSharpieOne** [comment]
Can you post a plunkr/fiddle/codepen of showing this issue or at least some code here that causes this issue.

**Comment by mkoczorowski** [comment]
I have the same issue. Any solution here?

**Comment by TheSharpieOne** [comment]
The solution is to post your code somewhere (plunkr/jsfiddle/codepen) so I can take a look and see what the issue actually is.

**Comment by RicardoAlmeidaMarques** [comment]
Resolved.
