### ISSUE TITLE
ES6 w/Babel and off-click-filter as a helper directive, with a factory for caching

### ISSUE THREAD

**Issue by RicardoAlmeidaMarques** [TheSharpieOne/angular-off-click#39]
I want to bring in [this commit](https://github.com/RicardoAlmeidaMarques/angular-off-click/commit/1bd1e296409f4aaa526778a1e6d27517e40f992b), with a simple gulp task to transpile, plus serve a minified version.
@TheSharpieOne Is this ok?

**Comment by RicardoAlmeidaMarques** [comment]
#40

**Comment by RicardoAlmeidaMarques** [comment]
to build : `npm run build` or `grunt build`

**Comment by TheSharpieOne** [comment]
Yeah, looks good. Gulp instead of grunt though.

**Comment by RicardoAlmeidaMarques** [comment]
Woops! Muscle memory.
