### ISSUE TITLE
off-click-filter not working with ng-repeat

### ISSUE THREAD

**Issue by zlovin** [TheSharpieOne/angular-off-click#42]
Think the problem with off-click-filter and ng-repeat is back, at least in my use-case. I believe it has to do with the es6 revision of angular-off-click not using the document query selector anymore. I don't have a codepen or plunkr to demonstrate, but here's my setup code and the console output I've seen from debugging:

![screen shot 2016-06-09 at 10 25 37 am](https://cloud.githubusercontent.com/assets/8484077/15935381/a97cb6fe-2e2c-11e6-8936-62262858f28e.png)

I have a custom directive `<toolbar-separator>` that I pass in a name to ("document" in this case) and inside the directive the id of the div gets set to that (via `<div id={{ctrl.name}}>`). So the end result in the html is:
```
<toolbar-separator>
   <div id="#document"> ... </div>
</toolbar-separator>
<ul off-click-filter="'#document'">
   <li ng-repeat=""> ... </li>
</ul>
```
![screen shot 2016-06-09 at 10 32 11 am](https://cloud.githubusercontent.com/assets/8484077/15935618/7d6dfc16-2e2d-11e6-8edd-c248ba674790.png)

So, the html is generated correctly.

The goal is for the toolbar-separator to be a modular toggle that expands a toolbar, and the `<ul>` below it is an associated area that has controls visible when the toollbar is expanded. Thus, clicking on the `<ul>` area should not deactivate the toolbar.

In the console however, I see this:
![screen shot 2016-06-09 at 10 31 27 am](https://cloud.githubusercontent.com/assets/8484077/15935573/656369e4-2e2d-11e6-9d82-d0ce99ad8129.png)

As you can see, the target is correct (when clicking on the `<ul>`), but the currentElem is wrong - it's using the element without the ng-repeated items inside of it and so it doesn't match.

If there's anything else I can do to clarify or assist, don't hesitate to let me know.

**Comment by Ricardo-Marques** [comment]
@zlovin off-click-filter accepts a string of comma separated selectors, meaning if your id is `#document`, you would have to point to `##document`

**Comment by Ricardo-Marques** [comment]
According to your comment where you say the toolbar-separator compiles to
```
<toolbar-separator>
   <div id="#document"> ... </div>
</toolbar-separator>
```
then yes, it should required 2 hashes

**Comment by zlovin** [comment]
I wrote that wrongly, the id is just {{ctrl.name}} so it comes out to 
`<div id="document"> ... </div>`

After a bit more digging around and debugging, I've tried to rule out some things.
First, I'm not using JQuery in my project, just relying on angular's jqlite so I'm not sure that the .contains() function in targetInFilter is working properly (see https://docs.angularjs.org/api/ng/function/angular.element). When I tried to use lodash's _.keys() function on the currentElem, it said that there were no keys, so I'm not sure there are functions available.
Second, I noticed that the classes on the currentElem are different than the classes on the target. I think that may have to do with initialization, or the fact that I'm using angular material. 

Here's an example: 
![screen shot 2016-06-09 at 12 55 23 pm](https://cloud.githubusercontent.com/assets/8484077/15940391/7d6d2660-2e41-11e6-931b-df0041d8e0c6.png)

Plan A: I added in the red 'blah' box as an item that has an off-click-filter for '#document' on it, like the Resume card does. In the console at the first currentElem part, the lefthand element has 'layout flex' as attributes, but the righthand target has both 'layout flex' attrs and 'layout-row flex' classes.

So, plan B: Add 'layout-row flex' as classes from the start instead of relying on material to make them:
![screen shot 2016-06-09 at 12 58 44 pm](https://cloud.githubusercontent.com/assets/8484077/15940492/f0121dc4-2e41-11e6-9831-82554ecccbcf.png)

Exact same problem. Now the element and target look identical, but it still returns false.

Plan C: Add JQuery into my project and see if it fixes the problem. Still broken.

Plan D: Test out the .contains() function.
![screen shot 2016-06-09 at 1 01 30 pm](https://cloud.githubusercontent.com/assets/8484077/15940681/bd25aba0-2e42-11e6-812c-ad32b409f659.png)

I made a smaller, nested box inside of my other box, maybe .contains() wasn't working because it was the root element or something? Still returns false for contains. Now I'm just really confused.

**Comment by Ricardo-Marques** [comment]
If it's not too much of hassle, could you setup a fiddle or similar where I could see this happening?

**Comment by zlovin** [comment]
@Ricardo-Marques Here's a plunkr: https://plnkr.co/edit/qwxC7oE93wC7w2VsUzOO?p=preview
For some reason it works in the plunker though, and it doesn't work for my local. Everything is basically the same. Hover over the 'Documents' toobar and an icon will show up on the right, click it to open the toolbar options. Clicking on the card or the box should keep the toolbar open, clicking outside of those should close it. 

So, I need to find out why it works there but not on my local development environment. Culprit #1 is that when I hover over the currentElem in the plunker, it highlights it. It doesn't highlight it in mine.

**Comment by Ricardo-Marques** [comment]
@zlovin Could I bother you to make a PR? :)

**Comment by Ricardo-Marques** [comment]
@zlovin Pushed with your fix, can you confirm it's working with the latest V1.0.2 ?

**Comment by Ricardo-Marques** [comment]
Also, I'm 99% sure the reason this issue was happening in the first place is the other directives on the element with off-click-filter altering the element during pre-link (which is something I should've considered)

**Comment by zlovin** [comment]
@Ricardo-Marques I'll check it out tomorrow, don't have the time to do it tonight. I did run into an issue earlier though with the destroy function that was fixed by changing it back to elem[0] instead of element[0], I'll see if that problem persists tomorrow.

I'm not too versed in the pre-link and post-link and compile stuff, so this has mostly been fumbling about on my part haha.

**Comment by zlovin** [comment]
@Ricardo-Marques I can confirm that the fix and v1.0.2 works for my application. I have another issue that might be related now, however. I've updated the plunker (and cleaned up some of the coffeescript -> javascript code): https://plnkr.co/edit/UaOv3Ru602ewG9iTwVqS?p=preview

When the toolbar is opened, a triple vertical dot menu is available on the card. Clicking it opens a menu. The menu has two items that use ng-click to call controller functions, editDialog and removeDialog. For simplicity's sake, I just added them to demoCtrl and they should log to console a string, but they never get called.

As a sanity check, I also added in the openDocument function, when you click on the icon or the document's name it logs 'opening document', and that works regardless of whether or not the toolbar is open. So, maybe it's an odd interaction between angular-off-click and angular materia's mdMenu, probably caused by the menu doing some odd stuff with the DOM tree because it inserts the menu's html inside the <body> tag rather than inside the <li> element. I've fixed that by adding in another off-click-filter on the <md-menu-content>. 

However, an error is thrown on $destroy when the menu is closed normally, because inside the $destroy function the element is set to equal null and there is some misc. cleanup that angular-material does that seems to get messed up because the element was nulled. By commenting out `element = null` on line 131 of offclick.js, the error wasn't thrown. Is the element set to null as a cleanup / memory leak 'fixer'?

**Comment by Ricardo-Marques** [comment]
@zlovin in your demo plunker the controller functions for the card menu execute for me.

As for `element = null` I'm fairly certain that's to force js garbage collection, but @TheSharpieOne might know of something I don't. Definitely an interesting issue though,

**Comment by AesSedai** [comment]
@Ricardo-Marques Yeah, it wasn't working originally until I put in the off-click-filter on the `md-menu-content`, accidentally fixed it in the process of writing the last message. 

As far as the `element = null`, things still function but it's likely not desired behavior for the material component to fail its cleanup.

**Comment by zlovin** [comment]
@Ricardo-Marques Yeah, it wasn't working originally until I put in the off-click-filter on the md-menu-content, accidentally fixed it in the process of writing the last message.

As far as the element = null, things still function but it's likely not desired behavior for the material component to fail its cleanup.
