### ISSUE TITLE
[Request] Add off-click-ignore attribute

### ISSUE THREAD

**Issue by zlovin** [TheSharpieOne/angular-off-click#44]
I have a use-case in my Angular Material application where I use mdDialog and mdMenu, which inserts html into the dom in document root by default instead of in the tree where they're in the html code at. I would like to propose an off-click-ignore attribute that doesn't trigger the off-click function no matter what, as if it was an off-click-filter except it filters everything.

**Comment by Ricardo-Marques** [comment]
`off-click-if` accepts a boolean and the expression in `off-click` will only execute if it's truthy.
Is that what you're looking for?

**Comment by AesSedai** [comment]
@Ricardo-Marques Functionally that would work, yes. In the case I had in mind for it though, implementing `off-click-if` would be a hassle though because it would require coupling the `off-click-if` inside the `<toolbar-separator>` (from the example in #42) to the state of the dialog, which is undesirable because it would break responsibility and introduce inter-directive dependencies. 

I think I'll look at implementing it `off-click-ignore` myself, and see if it's feasible and reasonable.

**Comment by zlovin** [comment]
@Ricardo-Marques Functionally that would work, yes. In the case I had in mind for it though, implementing off-click-if would be a hassle though because it would require coupling the off-click-if inside the <toolbar-separator> (from the example in #42) to the state of the dialog, which is undesirable because it would break responsibility and introduce inter-directive dependencies.

I think I'll look at implementing it off-click-ignore myself, and see if it's feasible and reasonable.

**Comment by Ricardo-Marques** [comment]
@zlovin so just to make sure I fully understand - You want a global off-click-filter that acts as a filter to every off-click?

**Comment by zlovin** [comment]
@Ricardo-Marques Yep, that's exactly it.

**Comment by Ricardo-Marques** [comment]
I can easily implement this. @TheSharpieOne Do you see any issue with making an array on the cache factory under `.__global` that filters every off-click?

**Comment by TheSharpieOne** [comment]
Yeah, that works, or I was originally thinking something like `off-click-filter="*"` and having that be a special case which would always be combined with the [other filters](https://github.com/TheSharpieOne/angular-off-click/blob/master/src/directives/offClick.js#L48-L55) (if it exists).
Just adding something like this after line 55 and documenting.
```
if(OffClickFilterCache['*']) filters = filters.concat(OffClickFilterCache['*']);
```

**Comment by Ricardo-Marques** [comment]
Added to v1.0.3
