### ISSUE TITLE
offClickFilter: scope.$on $destroy causing cannot read property '0' of null error

### ISSUE THREAD

**Issue by zlovin** [TheSharpieOne/angular-off-click#45]
Ran into this problem in the other issue I submitted, but since the problem in that issue was resolved I felt it better to open this up as a separate issue. 

In the scope.$on destroy, setting `element = null` is causing a problem with removing filters from the cache. Here's a plunkr demonstrating the issue: https://plnkr.co/edit/SJbU08nQUHcD4yUT3y60?p=preview

Clicking outside of the boxes causes the menus to not be shown and triggers their $destroy functions and throws the aforementioned error. By removing `element = null` things seemed to work as intended.

**Comment by TheSharpieOne** [comment]
The `element = null` just needs to be moved to after the `filters.forEach` stuff which happens right after `element` is set to `null` but depends on `element`.

**Comment by TheSharpieOne** [comment]
This is now fixed in master. It will be included in the next release [that @Ricardo-Marques does 😄].

**Comment by zlovin** [comment]
@Ricardo-Marques Could I pester you for a new release with this fix in it?

**Comment by Ricardo-Marques** [comment]
@TheSharpieOne @zlovin Sorry I let this one through. Thanks for catching it.
1.0.5 is on NPM.
