### ISSUE TITLE
Action on trigger is really slow

### ISSUE THREAD

**Issue by Xspirits** [TheSharpieOne/angular-off-click#7]
Hello,

Thanks for the work, it's a great idea and really helpful.
I tried to use your plugin, but I couldn't make it work in a way it's viable for production.

When I click outside of the element, it takes at least 1scd+ to hide the element.
I believe that's due to the angular and digest lifecycle and I was wondering if you think you could find a workaround (I couldn't fix it).

Best regards.

**Comment by TheSharpieOne** [comment]
Can you provide a fiddle or something with this happening.  I have http://jsfiddle.net/TheSharpieOne/zqh3vdno/ but am not seeing a noticeable delay.

The directive is very simple and doesn't do anything more than call your function, and doesn't wait until the digest to do so.  If anything in scope is changed in the function called (your function), it would wait until the digest to be render.
The callback function is passed to `$apply()`, but you can see [here](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#life-cycle) and [here](https://github.com/angular/angular.js/blob/master/src/ng/rootScope.js#L1025) that `$apply()` calls the function right away and then runs a digest immediately afterwards. From that point it is all angular.

Without seeing any of your code, it could be one of these things, which some are outside of this directive
+ Having too many of items (1,000+ items) in the scope will cause digests to take long.
+ You may be using css animation which could cause a delay when hiding/showing.
+ Passing too many items (10,000+ items) to the filter (directive loops over them)
+ Having too many elements (1,000,000+ elements) within the element that has this directive (node.contains (native function) loops over them)

**Comment by basvanmeurs** [comment]
I wanted to use your plugin for a project but it made the whole thing so slow that we were forced to remove it again. With only a dozen of items with off-click attributes.
